---
- name: Converge
  hosts: all
  tasks:
    - name: Update APT
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
  
    - name: "Include auditd_role"
      include_role:
        name: "auditd_role"
